<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="receivePO"
     targetNamespace="http://oracle.com/sca/soapservice/POProcessing/Project1/receivePO"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:inp1="http://xmlns.oracle.com/ns/order"
     xmlns:tns="http://oracle.com/sca/soapservice/POProcessing/Project1/receivePO"
    >
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/ns/order" schemaLocation="xsd/po.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="request" element="inp1:PurchaseOrder"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="execute">
            <wsdl:input message="tns:requestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
